config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "contributes#index"
  post "contribute/@contribute" => "contributes#create"
  get "contribute/classify" => "contributes#classify"
  resources :contributes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contribute.rb
class Contribute < ApplicationRecord
#  belongs_to :user
  require 'carrierwave/orm/activerecord'
  mount_uploader :video, VideoUploader
  mount_uploader :image, ImageUploader
  validates :videoname,:video,:image,:videoclass,presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
#  has_many :contributes
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contributes_controller.rb
class ContributesController < ApplicationController
  def index
    @contributes=Contribute.all
  end
  def new
    @contribute=Contribute.new
  end
  def classify
    @contributes=Contribute.where("videoclass=?",params[:videoclass]).take
  end
  def create
    @contribute=Contribute.new(contribute_params)
    if @contribute.save
      redirect_to :action => :index
    else
      render 'new'
    end
  end
  def show
    @contribute = Contribute.find(params[:id])
  end
  private
  def contribute_params
    params.require(:contribute).permit(:videoname,:video, :image, :command, :videoclass)
  end
end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contribute_helper.rb
module ContributeHelper
end

app/views/contributes/classify.html.erb
<div class="row m-2">
  <div class="col-sm-6 col-md-3 m-5">
    <a href="<%= contribute_path(@contributes) %>" class="imgshow">
      <%= image_tag @contributes.image, size: "250x154" %>
      <h6 class="desc"><%= @contributes.videoname %></h6>
    </a>
  </div>
</div>
<nav aria-label="Page navigation" >
  <ul class="pagination pagination-lg">
    <li>
      <a href="#" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    <li><a href="#">1</a></li>
    <li><a href="#">2</a></li>
    <li><a href="#">3</a></li>
    <li><a href="#">4</a></li>
    <li><a href="#">5</a></li>
    <li>
      <a href="#" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
  </ul>
</nav>

app/views/contributes/index.html.erb
<div class="container">
  <div class="col-md-12 col-lg-12 align-self-center col-xl-12 text-center">
    <div class="btn-group w-100">
      <%= link_to '番剧',{:controller => 'contributes', :action =>'classify', :videoclass => 'bangumi'}, :class => "btn btn-outline-info text-center border border-primary w-25 text-dark" %>
      <%= link_to '动画',{:controller => 'contributes', :action =>'classify', :videoclass => 'douga'}, :class => "btn btn-outline-info text-center border border-primary w-25 text-dark" %>
      <%= link_to '音乐',{:controller => 'contributes', :action =>'classify', :videoclass => 'music'}, :class => "btn btn-outline-info text-center border border-primary w-25 text-dark" %>
      <%= link_to '游戏',{:controller => 'contributes', :action =>'classify', :videoclass => 'game'}, :class => "btn btn-outline-info text-center border border-primary w-25 text-dark" %>
    </div>
  </div>
</div>
<div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <div id="myCarousel" class="carousel slide w-100 h-100" data-ride="carousel">
            <div class="carousel-inner w-100 h-100" role="listbox">
              <div class="carousel-item">
                <a href="">
                <img class="d-block img-fluid" src="<%= asset_path("02.jpg") %>" data-holder-rendered="true">
                <div class="carousel-caption">
                  <h3>题目</h3>
                  <p>介绍。。。。</p>
                </div>
              </a>
              </div>
              <div class="carousel-item active">
              <a href="">
                <img class="d-block img-fluid" src="<%= asset_path("03.jpg") %>" data-holder-rendered="true">
                <div class="carousel-caption">
                  <h3>题目</h3>
                  <p>介绍。。。。</p>
                </div>
              </a>
              </div>
            </div>
            <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev"> <span class="carousel-control-prev-icon" aria-hidden="true"></span> <span class="sr-only">Previous</span> </a>
            <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next"> <span class="carousel-control-next-icon" aria-hidden="true"></span> <span class="sr-only">Next</span> </a>
          </div>
        </div>
        <div class="col-md-3 w-25 h-100">
          <div class="responsive">
              <a href="#" class="imgshow">
                <img src="<%= asset_path("04.jpg") %>" width=100% height=144>
                <h6 class="desc">推广</h6>
              </a>
          </div>
          <div class="responsive">
              <a href="#" class="imgshow">
                <img src="<%= asset_path("05.jpg") %>" width=100% height=144>
                <h6 class="desc">推广</h6>
              </a>
          </div>
        </div>
        <div class="col-md-3 w-25 h-100">
          <div class="responsive">
             <a href="#" class="imgshow">
                <img src="<%= asset_path("08.jpg") %>" width=100% height=144>
                <h6 class="desc">推广</h6>
              </a>
          </div>
          <div class="responsive">
              <a href="#" class="imgshow">
                <img src="<%= asset_path("07.jpg") %>" width=100% height=144>
                <h6 class="desc">推广</h6>
              </a>
          </div>
        </div>
      </div>
    </div>
  </div>
<div class="row">
  <% @contributes.each do |i| %>
    <div class="col-sm-6 col-md-3">
      <a href="<%= contribute_path(i) %>" class="imgshow">
          <%= image_tag i.image, size: "250x154" %>
          <h6 class="desc"><%= i.videoname %></h6>
      </a>
    </div>
  <% end %>
</div>
<nav aria-label="Page navigation" >
  <ul class="pagination pagination-lg">
    <li>
      <a href="#" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    <li><a href="#">1</a></li>
    <li><a href="#">2</a></li>
    <li><a href="#">3</a></li>
    <li><a href="#">4</a></li>
    <li><a href="#">5</a></li>
    <li>
      <a href="#" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
  </ul>
</nav>

app/views/contributes/new.html.erb
<div class="container m-5">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
    <h1 class="size1">投稿</h1></br>
      <%= form_for @contribute,:html => {:multipart => true} do |a| %>
        <div class="form-group w-50">
          <label class="size1">稿件名</label>
          <%= a.text_field :videoname, :class => "form-control" , :required => "required" %>
        </div>
        <div class="form-group">
          <label class="size1">视频文件</label>
          <%= a.file_field :video, :required => "required" %>
        </div>
        <div class="form-group">
          <label class="size1">视频封面图片</label>
          <%= a.file_field :image, :required => "required" %>
        </div>
        <div class="form-group">
          <label class="size1">视频简介</label>
          <%= a.text_field :command, :class => "form-control", :required => "required" %><br>
        </div>
        <div class="form-group">
          <label class="size1">选择分类</label><br>   
          <div class="btn-group brn-group-lg" data-toggle="buttons" required="required" >
	          <label class="btn btn-info">
		          <%= a.radio_button(:videoclass, "douga") %>
		          <%= a.label(:videoclass_douga, "动画") %>
	          </label>
	          <label class="btn btn-info">
		          <%= a.radio_button(:videoclass, "bangumi") %>
		          <%= a.label(:videoclass_bangumi, "番剧") %>
	          </label>
	          <label class="btn btn-info">
		          <%= a.radio_button(:videoclass, "music") %>
		          <%= a.label(:videoclass_music, "音乐") %>
	          </label>
	          <label class="btn btn-info">
		          <%= a.radio_button(:videoclass, "game") %>
		          <%= a.label(:videoclass_game, "游戏") %>
	          </label>
          </div>
        </div>	
        <%= a.submit "上传", :class => "btn btn-primary btn-lg" %>
      <% end %>
    </div>
  </div>
</div>

app/views/contributes/show.html.erb
<div class="container m-5">
  <h1 class="size2"><%= @contribute.videoname %></h6>
  <video width="800" height="600" controls autoplay>
    <source src="<%= @contribute.video %>">
  </video>
  <p class=size1>简介：<%= @contribute.command %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Poipoipoi</title>
    <%= csrf_meta_tags %>
    <style>
    h6.desc
    {
      padding:5px;
      text-align:center;
    }
    a.imgshow
    {
      border: 1px solid #FFFFFF;
      border-radius:10px;
      padding:3px;
      float: left;
      width: 200;
      color: black;
      
    }
    a.imgshow:hover
    {
      border:1px solid #00FFCC;
      border-radius:10px;
      padding:3px;
      text-decoration:none;
      color:#00FFCC;
    }
    h1.size1{
      font-size:60px;
      text-align:center;
    }
    h1.size2{
      font-size:60px;
      text-align:left;
    }
    h1.size3{
      font-size:35px;
      text-align:center;
    }
    .size1{font-size:15px;}
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    </style>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://pingendo.com/assets/bootstrap/bootstrap-4.0.0-beta.1.css" type="text/css"> </head>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="w-100 m-0 p-0  text-right" style="background-image: url('<%= asset_path("32.jpg") %>');height:200px">
    <div class="btn-group text-white gradient-overlay m-1 text-right">
      <% if user_signed_in? %>       
        <button type="button" class="btn btn-default btn-sm">
	        <span class="glyphicon glyphicon-user">
	        </span>
	        <%= current_user.email %>
        </button> 
        <%= link_to "登出", destroy_user_session_path, :method => :delete, :class => "btn btn-dark text-white" %>    
      <% else %>    
        <%= link_to "注册", new_user_registration_path, :class => "btn btn-dark text-white" %>     
        <%= link_to "登录", new_user_session_path, :class => "btn btn-dark text-white" %>    
      <% end %>   
      <%= link_to '投稿',new_contribute_path, :class => "btn btn-dark text-white" %>
      <a href="#" class="btn btn-dark text-white">历史（未完成）</a>
      <a href="#" class="btn btn-dark text-white">收藏（未完成）</a>
      <%= link_to '返回首页', contributes_path, :class => "btn btn-dark text-white", :id => "to_index" %>    
    </div>
  </div>             
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <%= yield %>
        </div>
      </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
  </body>
</html>